[package]
name = "elfinfo"
version = "0.1.0"
authors = ["d4wnin9 <d4wnin9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"